# Drop-down terminal settings
set $term foot

# Launch and format the dropdown terminal
exec $term -t "Dropdown Terminal"

for_window [title="Dropdown Terminal"] {
    floating enable
    border none
    resize set width 100 ppt height 40 ppt
    move absolute position center
    move to scratchpad
}

# Keybinding to toggle the dropdown (e.g., F12) bindsym Mod1+q
bindsym F12 [title="Dropdown Terminal"] scratchpad show